# Site settings
title: VerUX
email: veruxdev@gmail.com
phone: 559.300.2834
url: https://reyvera.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Software Engineer - UX Designer - Musician"
meta_author: Vera Rey

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: verux

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 009688 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: VerUX
  location: Location
  social: Around the Web
  contact: Contact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ravera87
  - title: facebook
    url: https://www.facebook.com/rey.vera87
  # - title: stack-overflow
    # url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
    # url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/reyvera
  - title: linkedin-square
    url: https://www.linkedin.com/in/reymundovera

# Postal address (add as many lines as necessary)
address:
  - line: Bakersfield, CA

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'
contact:
  - line: 559.300.2834
  - line: veruxdev@gmail.com

# Build settings
markdown: kramdown
permalink: pretty
